BEGIN PROGRAM

DEFINE SIMULATION:
    SET ROUNDS 

    DEFINE HOUSE_RULES:
        TIE_BET IS TRUE, ODDS ARE 8:1
        DRAGON_BET IS TRUE, ODDS ARE 40:1
        CUT_BACK IS 14
        CUT_FRONT IS RANDOM(RANK)
        ENFORCE MINIMUM IS DEFAULT
        FREE HANDS IS DEFAULT

    DEFINE SHUFFLES: --COMPLETED
        SHOE IS SET
        SHUFFLE THE SHOE
        RETURN SHUFFLED_SHOE
        
    DEFINE BETS:
        PLAYER_BET IS DEFAULT
        BANKER_BET IS DEFAULT
        TIE_BET IS DEFAULT
        DRAGON_BET IS DEFAULT

    DEFINE STRATEGY:
        IF SHUFFLED_SHOE CONTAINS 25% TENS THEN
            SET TIE_BET TO ADJUSTED_VALUE
        ELSE IF SHUFFLED_SHOE CONTAINS 40% SEVENS THEN
            SET DRAGON_BET TO ADJUSTED_VALUE

        SET TOTAL_BET TO (PLAYER_BET OR BANKER_BET) + TIE_BET + DRAGON_BET
        RETURN TOTAL_BET

    DEFINE DRAW_RULES: 
	    ELABORATE ON THREE_CARD_RULE
	    ...
	    
    DEFINE CREATE_ROUND --in main
        SET ROUND
        SET SHUFFLED_SHOE
        SET STRATEGY
        SET BETS
        SET CARDS
        SET DRAW_RULES
        RETURN OUTCOME
        ADD ROUND
        IF ROUND >= ROUNDS
            END CREATE_ROUND

    DEFINE DISPLAY_RESULTS:
        OUT PLAYER_PROFIT_LOSS
        OUT DECK_COMPOSITIONS
        OUT OTHER DATA POINTS

DECIDE ON NEXT ACTION:
    IF CONDITION (e.g., USER WANTS TO RE-RUN) THEN
        RESTART PROGRAM
    ELSE 
        END PROGRAM
